### PR TITLE
Add compatibility for older versions of Windows and macOS

### PR DESCRIPTION
**Pull request by AdityaGarg8**
Someone on Windows 7 needs to test this though.

### CODE REVIEW

**Comment by rzc0d3r** [comment]
> Someone on Windows 7 needs to test this though.

I can install a virtual machine

**Comment by rzc0d3r** [comment]
> Someone on Windows 7 needs to test this though.

x32 or x64

**Comment by AdityaGarg8** [comment]
x64

**Comment by rzc0d3r** [comment]
I have already fixed this (there is now support for vindows 7). You need to install python 3.8.0 on github servers and compile everything on it

**Comment by rzc0d3r** [comment]
I suggest creating a portable build of python 3.8.0 win32 and uploading it to the cloud. And github servers will download it and use it for compilation.

**Comment by AdityaGarg8** [comment]
As long as it's working on 32bit and 64bit windows 7, looks good to me

**Comment by AdityaGarg8** [comment]
You didn't use portable python for 64bit, is that ok?

**Comment by AdityaGarg8** [comment]
I think windows 7 users can use the 32bit one on 64bit also

**Comment by rzc0d3r** [comment]
> Я думаю, что пользователи Windows 7 также могут использовать 32-битную версию на 64-битной.

This is what happens. win32 assembly is built on python 3.8.0 x32.  Works from windows7 SP1 and higher.  Win64 is built on python 3.9.13 x64, it no longer works on Windows 7.

**Comment by rzc0d3r** [comment]
I can remove the win64 build. Since win32 is actually universal

**Comment by AdityaGarg8** [comment]
I would prefer using the win64 one as it's made by latest python and tends to be more secure

**Pull request closed without merging**
