### PR TITLE
Add GitHub actions CI workflow

### PR DESCRIPTION
**Pull request by AdityaGarg8**
Using GitHub actions has been a massive success, so I thought of contributing my workflow file.

### CODE REVIEW

**Review by rzc0d3r — APPROVED** [review]

**Comment by AdityaGarg8** [comment]
No worries. You can try this workflow yourself in actions tab of your repo.

**Comment by rzc0d3r** [comment]
Nice

**Comment by AdityaGarg8** [comment]
It should show the key in the summary over here

https://github.com/rzc0d3r/ESET-KeyGen/actions/runs/7070842943

**Comment by AdityaGarg8** [comment]
Also in case you use it for your personal use, make sure you delete the run incident otherwise your key shall be publically visible.

**Comment by rzc0d3r** [comment]
Yes, I have seen this. Is it possible to add a function to the script that will change the date of the last test in README.md?

**Comment by AdityaGarg8** [comment]
It is possible. I'll try to get it done.

**Comment by AdityaGarg8** [comment]
We have 2 options here.

One: edit this workflow. This will cause the workflow to be restricted to your repo and if anyone forks this repo. Other repos won't be able to use it.

Second: Create a new workflow, named say test, which will also generate a key and an account, and update the time as well.

in the second case, you also have an option to either generate 1 or more license key, or choose to generate a particular number on every run, as per your wish. In this case, do you also want a summary?

What do you want?

**Comment by AdityaGarg8** [comment]
In 2, do you want to hardcode it to generate 1 account and 1 license key every time, or ask you the number of accounts and licenses to be generated

**Comment by rzc0d3r** [comment]
> We have 2 options here.
> 
> One: edit this workflow. This will cause the workflow to be restricted to your repo and if anyone forks this repo. Other repos won't be able to use it.
> 
> Second: Create a new workflow, named say test, which will also generate a key and an account, and update the time as well.
> 
> in the second case, you also have an option to either generate 1 or more license key, or choose to generate a particular number on every run, as per your wish. In this case, do you also want a summary?
> 
> What do you want?

You will need to use key generation in the script, as it will show if the project is working at 100%

**Comment by rzc0d3r** [comment]
> In 2, do you want to hardcode it to generate 1 account and 1 license key every time, or ask you the number of accounts and licenses to be generated

Only 1 license key. Without ask.

**Comment by AdityaGarg8** [comment]
Ok

**Comment by AdityaGarg8** [comment]
What time zone do you use to show time on your repo?

**Comment by rzc0d3r** [comment]
> What time zone do you use to show time on your repo?

Gmt+2

**Comment by AdityaGarg8** [comment]
Check https://github.com/rzc0d3r/ESET-KeyGen/pull/45

**Pull request merged**
