### PR TITLE
GitHub ci: Add support for both Intel and Apple Silicon Macs

### PR DESCRIPTION
**Pull request by AdityaGarg8**
GitHub changed the macos-latest runner image to M1 Macs. macOS 13 uses Intel.

### CODE REVIEW

**Comment by rzc0d3r** [comment]
Now available macos_arm64 and macos binary file?

**Comment by AdityaGarg8** [comment]
> Now available macos_arm64 and macos binary file?

The current macos binaries are for arm64 Macs, Intel Macs support has been readded in this PR.

**Comment by rzc0d3r** [comment]
I'll get to it tomorrow. I need to make updates to the code regarding these changes then as well..

**Comment by AdityaGarg8** [comment]
> The project has no code for the arm architecture.

your code is architecture independent. The github actions runner defined for macos in compile.yml runs on Apple M1 chip, which is an arm CPU. So, pyinstaller in that runner make the binary for arm

**Comment by rzc0d3r** [comment]
> > The project has no code for the arm architecture.
> 
> your code is architecture independent. The github actions runner defined for macos in compile.yml runs on Apple M1 chip, which is an arm CPU. So, pyinstaller in that runner make the binary for arm

I understand that. The problem here is that driver and project auto-update are based on the logic of architecture checking.

**Comment by AdityaGarg8** [comment]
image
I am getting this error with your current release.

**Comment by AdityaGarg8** [comment]
bad CPU type because the binaries are being compiled for arm

**Comment by AdityaGarg8** [comment]
> > > The project has no code for the arm architecture.
> > 
> > 
> > your code is architecture independent. The github actions runner defined for macos in compile.yml runs on Apple M1 chip, which is an arm CPU. So, pyinstaller in that runner make the binary for arm
> 
> I understand that. The problem here is that webdriver and project auto-update are based on the logic of architecture checking.

I got it. I pushed a change for auto update (https://github.com/rzc0d3r/ESET-KeyGen/pull/186/commits/d6154cf872f84fc21b15b9e4d3fd029eddf221c2). You can handle the driver.

**Comment by rzc0d3r** [comment]
All right. Uh-huh. We're on it. I changed my mind, haha.

**Comment by rzc0d3r** [comment]
Recommend some arm emulator MacOS for Windows amd64

**Comment by AdityaGarg8** [comment]
> Recommend some arm emulator MacOS for Windows amd64

??

**Comment by AdityaGarg8** [comment]
btw, this is the result of arm64 vs amd64

Screenshot 2024-05-20 at 10 55 27 PM

Screenshot 2024-05-20 at 10 56 49 PM

**Comment by AdityaGarg8** [comment]
> > > Recommend some arm emulator MacOS for Windows amd64
> > 
> > 
> > ??
> 
> if there's a way to put macOS arm on a virtual machine (Windows)

I haven't tried that ever. Is there anything specific you need that for?

**Comment by rzc0d3r** [comment]
> I haven't tried that ever. Is there anything specific you need that for?

I just want to test the code directly on the system so I can fix anything right away. IDK

**Comment by AdityaGarg8** [comment]
> > I haven't tried that ever. Is there anything specific you need that for?
> 
> I just want to test the code directly on the system so I can fix anything right away. IDK

You can use a github runner. I'll do a quick test.

**Comment by AdityaGarg8** [comment]
https://github.com/AdityaGarg8/random/actions/runs/9162743794/job/25190346348

This job tests both arm64 and amd64 on an Intel Mac.

**Comment by AdityaGarg8** [comment]
> Wtf image

wtf

**Comment by AdityaGarg8** [comment]
btw arm64 Macs for now support amd64 code as well as Apple has provided an in built emulator in them. So if you want to have only 1 binary, compile for amd64

**Comment by AdityaGarg8** [comment]
https://github.com/AdityaGarg8/random/actions/runs/9162812533/job/25190574281

This is the final test for amd64

**Comment by rzc0d3r** [comment]
> Wtf image

Fixed

**Comment by rzc0d3r** [comment]
> Кстати, компьютеры Mac с Arm64 сейчас поддерживают код amd64, и Apple предоставила в них встроенный эмулятор. Итак, если вы хотите иметь только один двоичный файл, скомпилируйте для amd64.

older systems don't support it, do they?

**Comment by AdityaGarg8** [comment]
https://github.com/AdityaGarg8/random/actions/runs/9162878827/job/25190796785

This is the test on arm64 with arm64 binary

**Comment by rzc0d3r** [comment]
Okey, so I'm keeping both binaries.

**Comment by rzc0d3r** [comment]
[ FAILED ] Traceback (most recent call last):
  File "main.py", line 341, in main
  File "modules/EsetTools.py", line 57, in createAccount
RuntimeError: 
ESET temporarily blocked your IP, try again later!!! TRY VPN!!!


NICE!!

**Comment by AdityaGarg8** [comment]
amd64 binary on arm64 is taking around 10 min for 1 key

**Comment by rzc0d3r** [comment]
> amd64 binary on arm64 is taking around 10 min for 1 key

hahaha

**Comment by AdityaGarg8** [comment]
> [ FAILED ] Traceback (most recent call last): File "main.py", line 341, in main File "modules/EsetTools.py", line 57, in createAccount RuntimeError: ESET temporarily blocked your IP, try again later!!! TRY VPN!!!
> 
> NICE!!

The binary doesn't have ur latest fix, thats why

**Comment by AdityaGarg8** [comment]
I just wanted to test whether they are working or not.

**Comment by rzc0d3r** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.4.9.0-test

**Comment by AdityaGarg8** [comment]
> https://github.com/rzc0d3r/ESET-KeyGen/releases/tag/v1.4.9.0-test

https://github.com/AdityaGarg8/random/actions/runs/9162929938/job/25190952885

**Comment by rzc0d3r** [comment]
Try ```--update``` argument

**Comment by AdityaGarg8** [comment]
> who's already edited it? I don't remember adding that. lmao
> 
> image

It was with this pr

**Comment by rzc0d3r** [comment]
> > who's already edited it? I don't remember adding that. lmao
> > image
> 
> It was with this pr

I didn't notice. I thought you only changed the yaml. Thx!!

**Comment by AdityaGarg8** [comment]
> who's already edited it? I don't remember adding that. lmao
> 
> image

image

**Comment by rzc0d3r** [comment]
and binary works?

**Comment by AdityaGarg8** [comment]
> > who's already edited it? I don't remember adding that. lmao
> > image
> 
> It was with this pr

https://github.com/AdityaGarg8/random/actions/runs/9162988261/job/25191165308

Test for update on arm64

**Comment by AdityaGarg8** [comment]
> and binary works?

I am still getting vpn error on my Mac

**Comment by rzc0d3r** [comment]
> > and binary works?
> 
> I am still getting vpn error on my Mac

hmm

**Comment by rzc0d3r** [comment]
run with ```--no-headless``` and check browser window

**Comment by rzc0d3r** [comment]
I guess I'm still getting the wrong password.

**Comment by AdityaGarg8** [comment]
> I guess I'm still getting the wrong password.

I got a key after trying again

**Comment by AdityaGarg8** [comment]
no I didn't

**Comment by rzc0d3r** [comment]
???

**Comment by AdityaGarg8** [comment]
image

**Comment by rzc0d3r** [comment]
> изображение

It happens, rarely, of course. The error is related to the selenium itself, it does not find the desired button, although it falls within the zone of visibility. still don't know how to fix it...

**Comment by AdityaGarg8** [comment]
image

**Comment by AdityaGarg8** [comment]
Thats chrome window when error is seen

**Comment by rzc0d3r** [comment]
Haha. good good. nope :(

**Comment by rzc0d3r** [comment]
it turns out the license request wasn't accepted.

**Comment by rzc0d3r** [comment]
Okey try another email-api. ```--email-api tempmail```

**Comment by rzc0d3r** [comment]
[patched-eset-tools.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/15380510/patched-eset-tools.zip)

**Comment by rzc0d3r** [comment]
try this crutch. extract to project folder with replace

**Comment by AdityaGarg8** [comment]
> Okey try another email-api. `--email-api tempmail`

**Comment by rzc0d3r** [comment]
Leave the default e-mail. But leave ```--no-headless```

**Comment by AdityaGarg8** [comment]
> Leave the default e-mail. But leave `--no-headless`

Can we do it later, its late here :)

**Comment by rzc0d3r** [comment]
You can

**Comment by AdityaGarg8** [comment]
Although, just in case its relevant, github actions are able to generate keys.

**Comment by rzc0d3r** [comment]
slightly different algorithms:
[ESET-KeyGen-v1.4.9.0-Dev.zip](https://github.com/rzc0d3r/ESET-KeyGen/files/15380676/ESET-KeyGen-v1.4.9.0-Dev.zip)

**Comment by rzc0d3r** [comment]
1000 commits!!
image

**Pull request merged**
