### PR TITLE
Create workflow to compile for macOS and Windows

### PR DESCRIPTION
**Pull request by AdityaGarg8**
You can now compile a binary for macOS and Windows. The version numbering is manual since I didn't understand how you do it. You can match it with your Windows release so that the macOS one gets released with it.

### CODE REVIEW

**Comment by rzc0d3r** [comment]
I'll sit down at my laptop soon and decide what to do about it.

**Comment by AdityaGarg8** [comment]
This issue still remains unsolved

https://github.com/rzc0d3r/ESET-KeyGen/issues/61

**Comment by AdityaGarg8** [comment]
Automatic version generation and release notes is technically possible, but you have to help me there as in how you generate them and stuff

**Comment by AdityaGarg8** [comment]
https://github.com/AdityaGarg8/ESET-KeyGen/releases/tag/v2.3.4.5-121212-3455

Test release made by the workflow I sent.

**Comment by AdityaGarg8** [comment]
You also needn't remove the workflow history of this as it does not generate any keys

**Comment by AdityaGarg8** [comment]
Linux binaries can also be made, but there are many Linux distros and binaries may not be cross compatible between 2 distros. Also, Linux has python installed, so binary is technically not really necessary.

**Comment by rzc0d3r** [comment]
> Автоматическое создание версий и примечаний к выпуску технически возможно, но вы должны помочь мне в том, как вы их создаете и все такое.

I can drop the dates in the version name.
You can also ask for the version name when running compile.yml

**Comment by AdityaGarg8** [comment]
> > Автоматическое создание версий и примечаний к выпуску технически возможно, но вы должны помочь мне в том, как вы их создаете и все такое.
> 
> I can drop the dates in the version name. You can also ask for the version name when running compile.yml

Can you please elaborate?

**Comment by rzc0d3r** [comment]
> > > Автоматическое создание версий и примечаний к выпуску технически возможно, но вы должны помочь мне в том, как вы их создаете и все такое.
> > 
> > 
> > Я могу опустить даты в названии версии. Вы также можете запросить имя версии при запуске compile.yml.
> 
> Можете ли вы уточнить?

Well, from now on, all future versions will be like this.
NOT ```v1.0.0.0 (XX XX XX XXXX XXXX-XXXX)``` just ```v1.0.0.0```.

**Comment by rzc0d3r** [comment]
> > > > Автоматическое создание версий и примечаний к выпуску технически возможно, но вы должны помочь мне в том, как вы их создаете и все такое.
> > > 
> > > 
> > > Я могу опустить даты в названии версии. Вы также можете запросить имя версии при запуске compile.yml.
> > 
> > 
> > Можете ли вы уточнить?
> 
> Well, from now on, all future versions will be like this. NOT `v1.0.0.0 (XX XX XXXX-XXXX)` just `v1.0.0.0`.

**Comment by AdityaGarg8** [comment]
I've removed the date

**Comment by rzc0d3r** [comment]
> I've removed the date

How do I specify the version of the output file? Will the script ask for it or what?

**Comment by AdityaGarg8** [comment]
Yes it will ask for version when you run the workflow.

**Comment by rzc0d3r** [comment]
> Yes it will ask for version when you run the workflow.

And another question: does it create a new release with the current code in the branch and with the binaries built?

**Comment by AdityaGarg8** [comment]
It will release with the latest code in the branch. If you have, an option to specifiy the commit hash can be added.

**Comment by rzc0d3r** [comment]
> It will release with the latest code in the main branch. If you have, an option to specifiy the commit hash can be added.

Is it very important?

**Comment by AdityaGarg8** [comment]
> > It will release with the latest code in the main branch. If you have, an option to specifiy the commit hash can be added.
> 
> Is it very important?

what is important?

**Comment by rzc0d3r** [comment]
> at is important?

commit hash for release.

**Comment by rzc0d3r** [comment]
> > at is important?
> 
> commit hash for release.

With commit hash you can see all the changes.

**Comment by AdityaGarg8** [comment]
> > at is important?
> 
> commit hash for release.

If your use case is like you release from an older version from the project, you need to specify the commit hash of that version

**Comment by rzc0d3r** [comment]
> If your use case is like you release from an older version from the project, you need to specify the commit hash of that version

Well, I'm not gonna do that. maybe :)

**Comment by AdityaGarg8** [comment]
Then the workflow should work just well

**Comment by rzc0d3r** [comment]
It's settled. I'm merging the code. OK?

**Comment by AdityaGarg8** [comment]
> It's settled. I'm merging the code. OK?

It should be fine

**Comment by AdityaGarg8** [comment]
You can do a test release after merging and test the exe

**Review by rzc0d3r — APPROVED** [review]

**Comment by rzc0d3r** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/actions/runs/7330038154

**Comment by AdityaGarg8** [comment]
What was the version you set?

**Comment by rzc0d3r** [comment]
> What was the version you set?

1.0.0.0 (TEST)

**Comment by AdityaGarg8** [comment]
You cannot put spaces or brackets

**Comment by rzc0d3r** [comment]
Maybe need "$name"

**Comment by AdityaGarg8** [comment]
Remove date commit made the versioning stricter

**Comment by AdityaGarg8** [comment]
You can revert that to add brackets

**Comment by AdityaGarg8** [comment]
Tag names cannot have brackets

**Comment by AdityaGarg8** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/commit/aaf29fb26b23fe39e1107dd6894b1536c04f0c16

Revert this commit, and put TEST in date

**Comment by AdityaGarg8** [comment]
If you don't want to revert, you also can do `1.0.0.0-TEST`

**Comment by rzc0d3r** [comment]
> If you don't want to revert, you also can do `1.0.0.0-TEST`

Everything works now. Thank you!

**Comment by AdityaGarg8** [comment]
The tag name variable is also good. You can use spaces and brackets in version and specify other name in tag name.

Have you tested the exe btw?

**Comment by rzc0d3r** [comment]
Not yet.

**Comment by rzc0d3r** [comment]
> The tag name variable is also good. You can use spaces and brackets in version and specify other name in tag name.
> 
> Have you tested the exe btw?

Works great!

**Pull request merged**
