### PR TITLE
Fix date formatting

### PR DESCRIPTION
**Pull request by AdityaGarg8**
I forgot to put the long year instead of short one

### CODE REVIEW

**Review by rzc0d3r — APPROVED** [review]

**Comment by rzc0d3r** [comment]
thx!

**Comment by AdityaGarg8** [comment]
Running test workflow should correct the time

**Comment by AdityaGarg8** [comment]
Is the time shown correct?

**Comment by AdityaGarg8** [comment]
Also, if you want to remove UTC+2 from the result, you can remove it from this line:

https://github.com/rzc0d3r/ESET-KeyGen/blob/main/.github/workflows/test.yml#L47

**Comment by AdityaGarg8** [comment]
Also, if possible, can you give me a brief on how your code actually works? As in, how did you get the esent website working and got the keys?

**Comment by rzc0d3r** [comment]
> Also, if you want to remove "UTC+2" from the result, you can remove it from this line:
> 
> https://github.com/rzc0d3r/ESET-KeyGen/blob/main/.github/workflows/test.yml#L47

let it be with a time zone.

**Comment by rzc0d3r** [comment]
> Also, if possible, can you give me a brief on how your code actually works? As in, how did you get the eset website working and got the keys?

There is nothing complicated about it. ESET itself provides a one month trial period (like all other commercial programs). To do this, you need to create a new account and make a request through the website, after which the license is automatically added to the account, and then the person receives a license for a month. It also comes to the email.

I have automated the process to the full 99.9 percent. All you have to do is click one button (Well almost :))

**Comment by AdityaGarg8** [comment]
That's what I wanted to know, how you got it done using a CLI. Also I tried to make an account on their website, but I never got an option for free trial.

**Comment by AdityaGarg8** [comment]
So how to convert this to a python script and removing the GUI need?

**Comment by rzc0d3r** [comment]
you can remove the browser window. But in some cases the site checks if the window is active. You can try

**Comment by AdityaGarg8** [comment]
What I meant was, how did you write the python scripts. They certainly make things easier. Like, did you reverse engineer the eset website? What do you do if the website gets changed?

**Comment by rzc0d3r** [comment]
> What I meant was, how did you write the python scripts. They certainly make things easier. Like, did you reverse engineer the eset website? What do you do if the website gets changed?

Yes, I've analyzed the site. I keep the algorithm up to date. During the time of public access to this repository and the past one, the site has been globally updated 3-4 times.

the most global and complex site update was for 11/16/2023

**Comment by AdityaGarg8** [comment]
I guess this is out of my scope then.

**Comment by rzc0d3r** [comment]
I stabilized the algorithm after that for 2-3 days.

**Comment by rzc0d3r** [comment]
The difficulty is that you can't run tests indefinitely. Maximum 12-15 times within 6-24 hours

**Comment by AdityaGarg8** [comment]
> The difficulty is that you can't run tests indefinitely. Maximum 12-15 times within 6-24 hours

Why is that so?

**Comment by rzc0d3r** [comment]
interesting fact: the first version of this project was created back in the summer of 2022

**Comment by rzc0d3r** [comment]
> > The difficulty is that you can't run tests indefinitely. Maximum 12-15 times within 6-24 hours
> 
> Why is that so?

The site blocks an IP address for multiple requests on the site

**Comment by AdityaGarg8** [comment]
I guess GitHub actions use dynamic IP (not sure though), so you are less likely to get banned there.

**Comment by AdityaGarg8** [comment]
Today I probably generated around 20 licensed using GitHub actions.

**Comment by rzc0d3r** [comment]
> Today I probably generated around 20 licenses using GitHub actions. Did a lot of testing.

Well, that's cool. I also recommend generating accounts so that licenses can be stored indefinitely )

**Comment by rzc0d3r** [comment]
and the keys to quickly reactivate the antivirus.

**Comment by AdityaGarg8** [comment]
I tried visited and registering using a temporary mail. Turns of my country is not eligible for free licenses, though I got an option for free license if country is changed to United States

**Comment by AdityaGarg8** [comment]
Interestingly the windows keys work for android as well

**Comment by rzc0d3r** [comment]
> I tried visiting the website and registering using a temporary mail. Turns out my country is not eligible for free licenses, though I got an option for free license if country is changed to United States

I noticed that a long time ago. So I added to the code the change of country to Ukraine. And now even blocked countries have access to the free license.

**Pull request merged**
