### PR TITLE
Add python script to reset eset vpn on Windows

### PR DESCRIPTION
**Pull request by AdityaGarg8**
Can be used to reset license on ESET VPN since it doesn't allow user to change its license

### CODE REVIEW

**Comment by AdityaGarg8** [comment]
I'm not sure how you will handle this, so I added the python script for the time being.

**Comment by rzc0d3r** [comment]
I'll include this in the next update

**Comment by rzc0d3r** [comment]
> Thanks.
> 
> Also for some reason I get error 500 when I try to open issues on your repo

I also had this recently when submitting a comment, apparently the internet is crumbling before eyes :)

**Comment by rzc0d3r** [comment]
Command line argument: ```--reset-eset-vpn```
Help: ```Trying to reset the license in the ESET VPN application [Windows only!!!]```

**Comment by rzc0d3r** [comment]
Can you verify the test code with yourself?

**Comment by AdityaGarg8** [comment]
Tested the latest release, it works!

**Comment by AdityaGarg8** [comment]
Now I am using ESET VPN to generate keys lol

**Pull request closed without merging**
