### PR TITLE
Add download links of antivirus and vpn in readme + Make universal binary for macOS

### PR DESCRIPTION
**Pull request by AdityaGarg8**

### CODE REVIEW

**Comment by AdityaGarg8** [comment]
Apple now supports making a universal binary for x86_64 and arm based macs, I've updated the code for the same.

**Comment by AdityaGarg8** [comment]
You will have to modify your updater as well, I didn't get how it works

**Comment by AdityaGarg8** [comment]
The reason I went for universal binary btw is because GitHub will soon depreciate the x86_64 based runners for GitHub actions.

**Comment by rzc0d3r** [comment]
> You will have to modify your updater as well, I didn't get how it works

In theory, you could just delete line 145 and line 146. And in 144 just write ```arch = 'macos'```

**Comment by AdityaGarg8** [comment]
> > You will have to modify your updater as well, I didn't get how it works
> 
> In theory, you could just delete line 115 and line 116. And in 114 just write `arch = 'macos'`
> 
> 

If you don't mind, can you do the changes 😅

**Comment by AdityaGarg8** [comment]
> > Apple now supports making a universal binary for x86_64 and arm based macs, I've updated the code for the same.
> 
> It will be work on arm64 and x86_64?

Yes, it works on both.

https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

**Review by rzc0d3r — APPROVED** [review]

**Comment by rzc0d3r** [comment]
As long as selenium supports python 3.8 all of this will work.

**Comment by AdityaGarg8** [comment]
> What do you think of the idea of removing the win64 build? And leave only Legacy (win32) which works on Windows 7 and 8, 10, 11?

I don't really mind as long as it works.

**Pull request merged**
