### PR TITLE
Add workflow to test run the code

### PR DESCRIPTION
**Pull request by AdityaGarg8**
You'll have to test it after merging. It shall be available as Test in Actions tab

### CODE REVIEW

**Review by rzc0d3r — APPROVED** [review]

**Comment by AdityaGarg8** [comment]
This workflow shall generated 1 account and 1 key, and update the time in your repo. You should check the summary after every test run and see whether both have been generated or not.

You can also change the ACCOUNT and KEY in the workflow file from 1 to some other value, if you want more number of ACCOUNTS/KEYS

**Comment by AdityaGarg8** [comment]
You seem to be having some security settings changed.

leeme figure out.

**Comment by AdityaGarg8** [comment]
image

**Comment by AdityaGarg8** [comment]
After this run the test action

**Comment by rzc0d3r** [comment]
https://github.com/rzc0d3r/ESET-KeyGen/actions/runs/7071177161

**Comment by AdityaGarg8** [comment]
You reran the previous instance. You need to run a new instance, like you did for the first time. Re-running previous workflow again makes it run with older settings.

also, make sure you did the setting I sent you.

**Comment by rzc0d3r** [comment]
Same error

**Comment by rzc0d3r** [comment]
Yes

**Comment by AdityaGarg8** [comment]
Then, goto settings>secrets and variables>actions>new repository secret

In name put PAT and in secret put your personal access token

**Comment by AdityaGarg8** [comment]
image

**Comment by AdityaGarg8** [comment]
Then change this line in test.yml 

https://github.com/rzc0d3r/ESET-KeyGen/blob/main/.github/workflows/test.yml#L53

From `github_token: ${{ secrets.GITHUB_TOKEN }}` to `github_token: ${{ secrets.PAT }}`

**Comment by AdityaGarg8** [comment]
Then run the test workflow (new run, not re run)

**Comment by AdityaGarg8** [comment]
> Then, goto settings>secrets and variables>actions>new repository secret
> 
> In name put PAT and in secret put your personal access token

In case you generate a token that expires, then make sure you update this secret with a new token after that expires.

In case you already are using a personal access token, then you can use that as well instead of generating a new one.

**Comment by AdityaGarg8** [comment]
`github_token:` Is repeated twice

**Comment by rzc0d3r** [comment]
ESET-KeyGen - Trial-Key & Account generator for ESET Antivirus (last test was on 02.12.23 at 18:39 UTC+2)

**Comment by rzc0d3r** [comment]
Works

**Pull request merged**
