### PR TITLE
Fixing chromedriver path for linux

### PR DESCRIPTION
**Pull request by Fasjeit**
#17

### CODE REVIEW

**Comment by rzc0d3r** [comment]
There is no need to explicitly specify the launch prefix.

check_output will automatically call the process with the OS prefix.

**Comment by rzc0d3r** [comment]
Lol i get same

**Review by rzc0d3r — CHANGES_REQUESTED** [review]
Pls Change:

'# Version 1.0.8.1 (131023-1557)' to '# Version 1.0.8.2 (131023-2039)'
'VERSION = 'v1.0.8.1 (131023-1557) by rzc0d3r' to 'VERSION = 'v1.0.8.2 (131023-2039) by rzc0d3r''

'out = check_output([chromedriver_name, "--version"], stderr=PIPE)' to
'out = check_output([os.getcwd()+'/'+chromedriver_name, "--version"], stderr=PIPE)'

**Review by rzc0d3r — APPROVED** [review]

**Comment by Fasjeit** [comment]
@rzc0d3r

Oh one more thing.

You can also consider changing the line 252 to 
```python
out = check_output([os.path.join(os.getcwd(), chromedriver_name), "--version"], stderr=PIPE)
```

which (by using `os.path.join`) shroud be more robust in theory but probably work the same.

**Comment by rzc0d3r** [comment]
Yes, it's probably safer that way. Because os.path.join takes into account which / was used

**Comment by rzc0d3r** [comment]
I changed the code and created a new release.

**Comment by rzc0d3r** [comment]
**Thank you for your support!!!**

**Pull request merged**
