### PR TITLE
Improve efficiency of CLI

### PR DESCRIPTION
**Pull request by AdityaGarg8**
Now the command needed to generated the licenses in run in parallel, so multiple licenses are simultaneously generated.

### CODE REVIEW

**Comment by AdityaGarg8** [comment]
The default number of accounts also has been set to 0 since rarely someone wants accounts.

I tried generating 10 license keys.

Before it took around 8min, now it takes only 2min

**Comment by AdityaGarg8** [comment]
Generating 10 accounts takes even shorter time.

**Comment by AdityaGarg8** [comment]
We can reduce time by around one more minute of there is a command that only sets up the chrome/firefox driver if ran.

**Comment by AdityaGarg8** [comment]
> We can reduce time by around one more minute if there is a command that only sets up the chrome/firefox driver if ran. Eg: `python3 main.py --driver-only --chrome`. You can help me in that.

I figured that out.

**Review by rzc0d3r — APPROVED** [review]

**Pull request merged**
